"""Test constants"""

BOOT_READY_PATTERN = "Device ready"
BOOT_TIMEOUT_SECONDS = 10
STATUS_MARKER = "[Status]"
STATUS_COMPLETION_MARKER = "Done"
DISTANCE_LOG_MARKER = "[Distance]"
DISTANCE_UNIT = "cm"
MIN_VALID_DISTANCE_CM = 0.0
LED_ON_COMMAND_ECHO = "LED ON"
